// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function useDidMount(f) {
  React.useEffect((function () {
          return Curry._1(f, /* () */0);
        }), /* array */[]);
  return /* () */0;
}

function useWillUnmount(f) {
  React.useEffect((function () {
          return (function (param) {
                    return Curry._1(f, /* () */0);
                  });
        }), /* array */[]);
  return /* () */0;
}

function useDidUpdate(f, conditions) {
  var didMoutRef = React.useRef(false);
  React.useEffect((function () {
          var match = didMoutRef.current;
          if (match) {
            return Curry._1(f, /* () */0);
          } else {
            didMoutRef.current = true;
            return undefined;
          }
        }), conditions);
  return /* () */0;
}

function useClock(param) {
  var match = React.useState((function () {
          return Date.now();
        }));
  var setDate = match[1];
  React.useEffect((function () {
          var ticker = setInterval((function (param) {
                  return Curry._1(setDate, (function (param) {
                                return Date.now();
                              }));
                }), 1000);
          return (function (param) {
                    clearInterval(ticker);
                    return /* () */0;
                  });
        }));
  return match[0];
}

exports.useDidMount = useDidMount;
exports.useWillUnmount = useWillUnmount;
exports.useDidUpdate = useDidUpdate;
exports.useClock = useClock;
/* react Not a pure module */
